server:
  port: 80

spring:
    application:
      name: consumer-dept-80

# Eureka配置
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/   # EurekaServer地址
  instance:
    instance-id: springcloud-consumer-dept-80
info:
  app.name: consumer-dept
  company.name: 神州泰岳
  author: viper_wu
