server:
  port: 8001

mybatis:
  type-aliases-package: com.viper.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

# Eureka配置
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true  # 向EurekaServer注册该服务
  instance:
    instance-id: springboot-provider-dept-8001 # 服务实例id
info:
  app.name: viper-springcloud
  company.name: 神州泰岳